### ISSUE TITLE
Barometer pressure not available on iOS 17.4

### ISSUE THREAD

**Issue by rwolff65** [justinchuby/barometer-project#8]
After an update of the Apple Watch the barometer pressure is not showing anymore in the watch. It is only showing altitude. In the phone it is still working. Watch OS 10.4

**Comment by justinchuby** [comment]
Thanks! I am looking into this

**Comment by justinchuby** [comment]
`CMAltimeter.authorizationStatus()` shows `notDetermined`, which I think prevents the app from getting measurement updates. Looks like this is something many people are facing: https://developer.apple.com/forums/thread/747797

**Comment by jmgray-sc** [comment]
Able to correct in iOS 17.4 for iPhone 13 Pro by adding permission:  Privacy - Motion Usage Description.  User will be prompted like any other permission, then CMAltimeter data flows like in past versions.  Seems to recognize the device pressure much quicker, at least in my instance.

**Comment by justinchuby** [comment]
https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources

**Comment by justinchuby** [comment]
@jmgray-sc I added the permission description string but it didn't seem to do anything. Was there more you had to configure?

**Comment by justinchuby** [comment]
Fix. Releasing soon.
